DELETE FROM ENTRENADORENTITY_USUARIOENTITY;
DELETE FROM MAQUINAENTITY_TIPOMEDIDAENTITY;
DELETE FROM EJERCICIOENTITY_MAQUINAENTITY;
DELETE FROM EJERCICIOENTITY_OBJETIVOENTITY;
DELETE FROM EJERCICIOENTITY_TIPOMEDIDAENTITY;
DELETE FROM USUARIOENTITY_OBJETIVOENTITY;
DELETE FROM EJERCICIOHECHOENTITY;
ALTER TABLE EJERCICIOHECHOENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM MEDICIONMAQUINAENTITY;

DELETE FROM EJERCICIOINSTANCIAENTITY;
ALTER TABLE EJERCICIOINSTANCIAENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM ATRIBUTODECALIDADENTITY;
ALTER TABLE ATRIBUTODECALIDADENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM EJERCICIOENTITY;
ALTER TABLE EJERCICIOENTITY ALTER COLUMN ID RESTART WITH 1;


DELETE FROM MEDIDAENTITY;
ALTER TABLE MEDIDAENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM ESTADOENTITY;
ALTER TABLE ESTADOENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM MAQUINAENTITY;
ALTER TABLE MAQUINAENTITY ALTER COLUMN ID RESTART WITH 1;


DELETE FROM OBJETIVOENTITY;
ALTER TABLE OBJETIVOENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM RUTINAENTITY;
ALTER TABLE RUTINAENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM TIPOMEDIDAENTITY;
ALTER TABLE TIPOMEDIDAENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM ENTRENADORENTITY;
ALTER TABLE ENTRENADORENTITY ALTER COLUMN ID RESTART WITH 1;

DELETE FROM USUARIOENTITY;
ALTER TABLE USUARIOENTITY ALTER COLUMN ID RESTART WITH 1;

INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('HOWARD', '3/28/1998', '100712578');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('BRENDON', '10/9/1978', '988785786');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('THEKLA', '11/17/1989', '1234789598');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('ORSA', '8/18/1997', '998856148');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('KEAN', '3/21/1980', '965789582');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('OBADIAH', '11/21/1993', '1282357442');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('ROYCE', '11/4/1978', '1257896358');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('BAX', '9/27/1958', '456850369');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('SILVA', '7/16/1999', '789581123');
INSERT INTO ENTRENADORENTITY (NOMBRE, FECHANACIMIENTO, DOCUMENTO) VALUES ('LESYA', '7/21/1989', '369785123');

INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('HERC', '11/18/2016', 1);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('DOLPH', '10/21/2016', 1);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('NATA', '12/22/2016', 1);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('SHERRIE', '8/15/2017', 1);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('NEALY', '11/2/2016', 0);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('RICA', '12/6/2016', 1);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('GENE', '3/6/2017', 1);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('JASUN', '2/2/2017', 0);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('DALSTON', '1/9/2017', 1);
INSERT INTO USUARIOENTITY (NOMBRE, FECHADENACIMIENTO, GENERO) VALUES ('WOLF', '7/4/2017', 0);

INSERT INTO ESTADOENTITY (FECHA,USUARIO_ID) VALUES ('7/4/2017',1);
INSERT INTO ESTADOENTITY (FECHA,USUARIO_ID) VALUES ('2/2/2017',1);
INSERT INTO ESTADOENTITY (FECHA,USUARIO_ID) VALUES ('3/6/2017',1);
INSERT INTO ESTADOENTITY (FECHA,USUARIO_ID) VALUES ('7/4/2017',2);
INSERT INTO ESTADOENTITY (FECHA,USUARIO_ID) VALUES ('8/15/2017',2);

INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (1,1);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (1,2);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (1,3);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (1,4);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (2,2);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (3,3);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (4,4);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (5,5);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (6,6);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (7,7);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (2,4);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (2,7);
INSERT INTO ENTRENADORENTITY_USUARIOENTITY (ENTRENADORES_ID,USUARIOS_ID) VALUES (2,5);

INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('TROTADORA');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('PRENSA DE PIERNAS');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('PARALELAS');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('RALLY WAGON 3500');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('ASCENDER');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('BARRAS');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('ODYSSEY');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('GRANTURISMO');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('TRAILBLAZER');
INSERT INTO MAQUINAENTITY (INFORMACION) VALUES ('E-350 SUPER DUTY');

INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (1,0,'10/1/2017','12/31/2017',1);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (2,0,'11/18/2016','11/18/2017',2);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (3,0,'11/18/2016','11/18/2017',3);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (4,0,'11/18/2016','11/18/2017',4);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (5,0,'11/18/2016','11/18/2017',2);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (6,0,'11/18/2016','11/18/2017',1);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (7,0,'11/18/2016','11/18/2017',1);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (8,0,'11/18/2016','11/18/2017',3);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (9,0,'11/18/2016','11/18/2017',3);
INSERT INTO RUTINAENTITY (ID,CUMPLIMIENTO,FECHAINICIO,FECHAFINAL,USUARIO_ID) VALUES (10,0,'11/18/2016','11/18/2017',1);

INSERT INTO EJERCICIOENTITY (DESCRIPCION,video,EXPLICACION,TIPO) 
VALUES ('Remo horizontal con mancuerna','n1Xb8ispJbs','Para empezar, hay que posicionarse, tomando una mancuerna con la mano izquierda o derecha, y apoyando la palma de la mano contraria, al igual que la rodilla sobre el banco. La espalda debe permanecer fija y el brazo con la mancuerna extendido hacia abajo, al costado del cuerpo.
Inspirar y elevar la mancuerna hasta la espalda, de forma que el codo quede por encima de la misma para imitar el movimiento de remo.
Regresar a la posición original en un movimiento controlado y lento, y espirar al final de recorrido.','AEROBICOS');
INSERT INTO APP.EJERCICIOENTITY (DESCRIPCION, EXPLICACION, TIPO, VIDEO) 
	VALUES ('Remo al cuello con polea baja', 'Uno de los ejercicios que vale la pena llevar a cabo en las rutinas de volumen muscular es el remo al cuello con polea baja, ya que ayuda a trabajar el tren superior, específicamente los músculos de los hombros.', 'ANEAROBICOS', 'SyX9QF76-c8');
INSERT INTO APP.EJERCICIOENTITY (DESCRIPCION, EXPLICACION, TIPO, VIDEO) 
	VALUES ('Encogimiento de hombros con mancuernas', 'Para su ejecución será necesario de un par de mancuernas de peso ajustado, según tus capacidades de levantamiento.', 'NO_PERTENECE', 'qlIv6nW5kHU');
INSERT INTO APP.EJERCICIOENTITY (DESCRIPCION, EXPLICACION, TIPO, VIDEO) 
	VALUES ('Mountain Climbers', 'un ejercicio que involucra los músculos de la cintura y que nos permiten elevar las piernas a la hora de saltar, golpear un balón o soltar una patada.', 'AEROBICOS', 'lvaQcFaxL00');
INSERT INTO APP.EJERCICIOENTITY (DESCRIPCION, EXPLICACION, TIPO, VIDEO) 
	VALUES ('Abdominales en barra', 'para hacerlo bien es necesario tener un perfecto control abdominal y una amplia concentración en la zona que estamos trabajando.', 'EQUILIBRIO', 'hCRrA-EAiBU');

INSERT INTO EJERCICIOINSTANCIAENTITY (DURACION,CUMPLIMIENTO,SERIES,REPETICIONESPORPARTICION,TAMANIOPARTICIONES,EJERCICIO_ID,RUTINA_ID) VALUES (15,0,20,1,7,1,1);
INSERT INTO EJERCICIOINSTANCIAENTITY (DURACION,CUMPLIMIENTO,SERIES,REPETICIONESPORPARTICION,TAMANIOPARTICIONES,EJERCICIO_ID,RUTINA_ID) VALUES (25,0,0,1,7,2,1);
INSERT INTO EJERCICIOINSTANCIAENTITY (DURACION,CUMPLIMIENTO,SERIES,REPETICIONESPORPARTICION,TAMANIOPARTICIONES,EJERCICIO_ID,RUTINA_ID) VALUES(20,0,30,3,7,3,1);
INSERT INTO EJERCICIOINSTANCIAENTITY (DURACION,CUMPLIMIENTO,SERIES,REPETICIONESPORPARTICION,TAMANIOPARTICIONES,EJERCICIO_ID,RUTINA_ID) VALUES(15,0,15,1,7,1,2);
INSERT INTO EJERCICIOINSTANCIAENTITY (DURACION,CUMPLIMIENTO,SERIES,REPETICIONESPORPARTICION,TAMANIOPARTICIONES,EJERCICIO_ID,RUTINA_ID) VALUES (15,0,20,2,7,1,3);
INSERT INTO EJERCICIOINSTANCIAENTITY (DURACION,CUMPLIMIENTO,SERIES,REPETICIONESPORPARTICION,TAMANIOPARTICIONES,EJERCICIO_ID,RUTINA_ID) VALUES (15,0,30,1,7,1,4);
INSERT INTO EJERCICIOINSTANCIAENTITY (DURACION,CUMPLIMIENTO,SERIES,REPETICIONESPORPARTICION,TAMANIOPARTICIONES,EJERCICIO_ID,RUTINA_ID) VALUES (15,0,20,3,7,1,5);

INSERT INTO EJERCICIOHECHOENTITY (FECHA,SERIESREALES,EJERCICIO_ID) VALUES ('11/11/2017',14,1);

INSERT INTO EJERCICIOENTITY_MAQUINAENTITY (EJERCICIOS_ID,MAQUINAS_ID) VALUES (2,1);
INSERT INTO EJERCICIOENTITY_MAQUINAENTITY (EJERCICIOS_ID,MAQUINAS_ID) VALUES (3,2);
INSERT INTO EJERCICIOENTITY_MAQUINAENTITY (EJERCICIOS_ID,MAQUINAS_ID) VALUES (1,1);
INSERT INTO EJERCICIOENTITY_MAQUINAENTITY (EJERCICIOS_ID,MAQUINAS_ID) VALUES (1,2);
INSERT INTO EJERCICIOENTITY_MAQUINAENTITY (EJERCICIOS_ID,MAQUINAS_ID) VALUES (1,3);
INSERT INTO EJERCICIOENTITY_MAQUINAENTITY (EJERCICIOS_ID,MAQUINAS_ID) VALUES (1,4);

INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('ESPALDA','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('ABDOMEN','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('PECHO','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('ANTEBRAZO','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('HOMBROS','C;',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('GLUTEOS','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('BICEP','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('OBLICUOS','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('TRICEP','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('TRAPECIOS','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('TELDOiDES','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('PIERNAS','CM',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('PESO','KG',0);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('VELOCIDAD PROMEDIO','KM/S',1);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('CALORIAS QUEMADAS','CAL',1);
INSERT INTO TIPOMEDIDAENTITY (TIPOMEDIDA,UNIDAD,AUTOMATICO) VALUES ('KILOMETROS REOCRIDOS','KM',1);

INSERT INTO MAQUINAENTITY_TIPOMEDIDAENTITY (MAQUINAS_ID,TIPOMEDIDA_ID) VALUES (1,5);
INSERT INTO MAQUINAENTITY_TIPOMEDIDAENTITY (MAQUINAS_ID,TIPOMEDIDA_ID) VALUES (1,6);
INSERT INTO MAQUINAENTITY_TIPOMEDIDAENTITY (MAQUINAS_ID,TIPOMEDIDA_ID) VALUES (1,7);

INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (12,1,1);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (13,2,1);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (13,3,1);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (15,4,1);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (16,5,1);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (37,1,2);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (36,2,2);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (37,3,2);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (27,1,3);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (26,2,3);
INSERT INTO MEDIDAENTITY (MEDIDA,ESTADO_ID,PARTE_ID) VALUES (28,3,3);

INSERT INTO OBJETIVOENTITY (TIPO,DESCRIPCION) VALUES ('ADELGAZAR','es una reducción de la masa corporal de un individuo, por razón de una pérdida promedio de líquidos, grasa o de tejidos como el músculo, tendón o tejido conjuntivo.');
INSERT INTO OBJETIVOENTITY (TIPO,DESCRIPCION) VALUES ('AUMNETAR LA MASA MUSCULAR','Los doctores afirman que puedes aumentar tu masa muscular de manera notoria en unas seis semanas después de empezar una rutina de ejercicios regular.');
INSERT INTO OBJETIVOENTITY (TIPO,DESCRIPCION) VALUES ('GANAR RESISTENCIA','La resistencia es una cualidad psicofísica que nos permite prolongar un ejercicio o una actividad.');
INSERT INTO OBJETIVOENTITY (TIPO,DESCRIPCION) VALUES ('TONIFICAR','Tonificar es sinónimo de endurecer, fortalecer, sin necesariamente aumentar la masa muscular en forma exagerada. Se puede estar delgado, pero tonificado.');

INSERT INTO USUARIOENTITY_OBJETIVOENTITY (OBJETIVOS_ID,USUARIOS_ID) VALUES (1,1);
INSERT INTO USUARIOENTITY_OBJETIVOENTITY (OBJETIVOS_ID,USUARIOS_ID) VALUES (1,2);
INSERT INTO USUARIOENTITY_OBJETIVOENTITY (OBJETIVOS_ID,USUARIOS_ID) VALUES (1,3);
INSERT INTO USUARIOENTITY_OBJETIVOENTITY (OBJETIVOS_ID,USUARIOS_ID) VALUES (1,4);
INSERT INTO USUARIOENTITY_OBJETIVOENTITY (OBJETIVOS_ID,USUARIOS_ID) VALUES (2,3);
INSERT INTO USUARIOENTITY_OBJETIVOENTITY (OBJETIVOS_ID,USUARIOS_ID) VALUES (2,5);

INSERT INTO EJERCICIOENTITY_OBJETIVOENTITY (EJERCICIOS_ID,OBJETIVOSEJERCICIO_ID) VALUES (1,1);
INSERT INTO EJERCICIOENTITY_OBJETIVOENTITY (EJERCICIOS_ID,OBJETIVOSEJERCICIO_ID) VALUES (2,1);
INSERT INTO EJERCICIOENTITY_OBJETIVOENTITY (EJERCICIOS_ID,OBJETIVOSEJERCICIO_ID) VALUES (2,3);
INSERT INTO EJERCICIOENTITY_OBJETIVOENTITY (EJERCICIOS_ID,OBJETIVOSEJERCICIO_ID) VALUES (3,1);
INSERT INTO EJERCICIOENTITY_OBJETIVOENTITY (EJERCICIOS_ID,OBJETIVOSEJERCICIO_ID) VALUES (3,2);
INSERT INTO EJERCICIOENTITY_OBJETIVOENTITY (EJERCICIOS_ID,OBJETIVOSEJERCICIO_ID) VALUES (3,3);

INSERT INTO EJERCICIOENTITY_TIPOMEDIDAENTITY (EJERCICIOS_ID,TIPOSMEDIDAS_ID) VALUES (1,1);
INSERT INTO EJERCICIOENTITY_TIPOMEDIDAENTITY (EJERCICIOS_ID,TIPOSMEDIDAS_ID) VALUES (1,2);
INSERT INTO EJERCICIOENTITY_TIPOMEDIDAENTITY (EJERCICIOS_ID,TIPOSMEDIDAS_ID) VALUES (1,8);
INSERT INTO EJERCICIOENTITY_TIPOMEDIDAENTITY (EJERCICIOS_ID,TIPOSMEDIDAS_ID) VALUES (2,1);
INSERT INTO EJERCICIOENTITY_TIPOMEDIDAENTITY (EJERCICIOS_ID,TIPOSMEDIDAS_ID) VALUES (2,2);

INSERT INTO ATRIBUTODECALIDADENTITY (REGRESION,OBJETIVO_ID,TIPOMEDIDA_ID)VALUES(1,1,1);
INSERT INTO ATRIBUTODECALIDADENTITY (REGRESION,OBJETIVO_ID,TIPOMEDIDA_ID)VALUES(1,1,2);
